repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: >
          ^(
              alembic/
          )$
        args: [--config=pyproject.toml]
        language_version: python3.10
  - repo: https://github.com/myint/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        exclude: >
          ^(
              alembic/
          )$
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort