version: '3.8'
services:
  chatgpt-bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-cache-chatgpt
    network_mode: host

  redis-cache-chatgpt:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass easyPassword
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local